// next-app/src/components/ui/Card.tsx
interface CardProps {
  padding?: 'none' | 'sm' | 'md' | 'lg';
  children: React.ReactNode;
  className?: string;
}

const paddingClasses = {
  none: '',
  sm: 'p-4',
  md: 'p-6',
  lg: 'p-8',
};

export default function Card({ padding = 'md', children, className = '' }: CardProps) {
  return (
    <div className={`bg-[var(--color-surface)] rounded-lg ${paddingClasses[padding]} ${className}`}>
      {children}
    </div>
  );
}

// src/lib/components/ui/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		padding?: 'none' | 'sm' | 'md' | 'lg';
		children: Snippet;
	}

	let { padding = 'md', children }: Props = $props();

	const paddingClasses = {
		none: '',
		sm: 'p-4',
		md: 'p-6',
		lg: 'p-8'
	};
</script>

<div class="bg-[var(--color-surface)] rounded-lg {paddingClasses[padding]}">
	{@render children()}
</div>
